# .github/FUNDING.yml

github: [linhprovip2002] # GitHub Sponsors username(s)
patreon: linhprovip2002   # Patreon username
open_collective: linhprovip2002 # Open Collective username
ko_fi: linhprovip2002     # Ko-fi username
tidelift: linhprovip2002   # Tidelift package name (if applicable)
community_bridge: linhprovip2002 # Community Bridge project name (if applicable)
liberapay: linhprovip2002  # Liberapay username (if applicable)
issuehunt: linhprovip2002   # IssueHunt username (if applicable)
lfx_crowdfunding: linhprovip2002 # LFX Crowdfunding project name (if applicable)
polar: linhprovip2002      # Polar username (if applicable)
buy_me_a_coffee: linhprovip2002 # Buy Me A Coffee username (if applicable)
thanks_dev: linhprovip2002  # thanks.dev username (if applicable)
custom: ['https://www.linkedin.com/in/levi-dang/'] # Replace with up to 4 custom sponsorship URLs if any
