blank_issues_enabled: false
contact_links:
  - name: ❓ Need help or have a question?
    url: https://github.com/CongNgheTriThucNC/Backend/discussions
    about: Please ask and discuss general questions in GitHub Discussions.
